name = "all-of-fabric-5"
author = "TeamAOF"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "249f3bc0b5766cc8f1e677ddae4071e06c847717dfeeaed17a230d90c9f1998e"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
