name = "all-of-fabric-5"
author = "TeamAOF"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe52500a10d152c7378c377233dff8847f0266066cdcee368e5677d745e9c322"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
